'use client';

import Link from 'next/link';

export default function TermsOfServicePage() {
  return (
    <div style={{ background: 'var(--bg-primary)', color: 'var(--color-text-primary)' }}>
      {/* ---------- Nav ---------- */}
      <nav
        className="fixed top-0 left-0 right-0 z-50 flex items-center justify-between px-6 py-4 backdrop-blur-md"
        style={{
          background: 'rgba(255, 251, 247, 0.85)',
          borderBottom: '1px solid var(--border-card)',
        }}
      >
        <Link href="/" className="flex items-center gap-2 no-underline">
          <span
            className="text-xl font-bold"
            style={{ color: 'var(--color-sage)' }}
          >
            Health
          </span>
          <span className="text-xl font-bold" style={{ color: 'var(--color-text-primary)' }}>
            Track
          </span>
        </Link>
        <Link
          href="/login"
          className="px-4 py-2 rounded-lg text-sm font-semibold no-underline transition-colors"
          style={{
            background: 'transparent',
            color: 'var(--color-sage)',
            border: '1px solid #4ADE80',
          }}
        >
          Sign In
        </Link>
      </nav>

      {/* ---------- Content ---------- */}
      <main className="max-w-3xl mx-auto px-6 pt-32 pb-20">
        <h1 className="text-3xl md:text-4xl font-bold mb-2">Terms of Service</h1>
        <p className="text-sm mb-12" style={{ color: 'var(--color-text-muted)' }}>
          Effective date: July 14, 2026
        </p>

        <div className="space-y-10">
          {/* 1. Acceptance of Terms */}
          <section>
            <h2 className="text-xl md:text-2xl font-bold mb-4">1. Acceptance of Terms</h2>
            <p className="leading-relaxed" style={{ color: 'var(--color-text-muted)' }}>
              By accessing or using this HealthTrack instance (the &quot;Service&quot;), you
              agree to be bound by these Terms of Service (&quot;Terms&quot;). If you do not
              agree to these Terms, you may not use the Service. HealthTrack is self-hosted
              software; this instance is operated by its administrator (&quot;we,&quot;
              &quot;our,&quot; or &quot;us&quot;).
            </p>
          </section>

          {/* 2. Description of Service */}
          <section>
            <h2 className="text-xl md:text-2xl font-bold mb-4">2. Description of Service</h2>
            <p className="leading-relaxed" style={{ color: 'var(--color-text-muted)' }}>
              HealthTrack is a health data tracking progressive web application (PWA) that allows you
              to record and organize medications, medical conditions, allergies, procedures, lab
              results, vital signs, appointments, and personal health notes. The Service also
              provides AI-powered health insights, lab PDF parsing, wearable device integration, and
              health data sharing features. HealthTrack is designed to help you organize and
              understand your health data. It does not provide medical advice, diagnoses, or treatment
              recommendations.
            </p>
          </section>

          {/* 3. Medical Disclaimer */}
          <section>
            <h2 className="text-xl md:text-2xl font-bold mb-4">3. Medical Disclaimer</h2>
            <div
              className="rounded-xl p-6 mb-4"
              style={{
                background: 'var(--bg-card)',
                border: '1px solid var(--color-caution)',
              }}
            >
              <p
                className="leading-relaxed font-semibold"
                style={{ color: 'var(--color-text-primary)' }}
              >
                HealthTrack is not a medical device. HealthTrack is NOT a substitute for
                professional medical advice, diagnosis, or treatment. Always seek the advice of
                your physician or other qualified health
                provider with any questions you may have regarding a medical condition. Never
                disregard professional medical advice or delay in seeking it because of something
                you have read or received through HealthTrack.
              </p>
            </div>
            <p className="leading-relaxed" style={{ color: 'var(--color-text-muted)' }}>
              The AI-powered insights and analysis provided by HealthTrack are for informational
              purposes only. They are generated by artificial intelligence and may contain errors or
              inaccuracies. AI responses should not be interpreted as medical advice. If you think
              you may have a medical emergency, call your doctor or emergency services immediately.
            </p>
          </section>

          {/* 4. Account Registration & Security */}
          <section>
            <h2 className="text-xl md:text-2xl font-bold mb-4">4. Account Registration &amp; Security</h2>
            <p className="leading-relaxed mb-3" style={{ color: 'var(--color-text-muted)' }}>
              To use HealthTrack, you must create an account using either an email address and
              password or Google OAuth. You are responsible for:
            </p>
            <ul className="list-disc list-inside space-y-2" style={{ color: 'var(--color-text-muted)' }}>
              <li>Providing accurate and complete registration information</li>
              <li>Maintaining the security and confidentiality of your login credentials</li>
              <li>All activities that occur under your account</li>
              <li>Notifying us immediately of any unauthorized use of your account</li>
            </ul>
            <p className="leading-relaxed mt-3" style={{ color: 'var(--color-text-muted)' }}>
              For your security, HealthTrack automatically logs you out after 15 minutes of
              inactivity.
            </p>
          </section>

          {/* 5. Acceptable Use */}
          <section>
            <h2 className="text-xl md:text-2xl font-bold mb-4">5. Acceptable Use</h2>
            <p className="leading-relaxed mb-3" style={{ color: 'var(--color-text-muted)' }}>
              You agree not to use HealthTrack to:
            </p>
            <ul className="list-disc list-inside space-y-2" style={{ color: 'var(--color-text-muted)' }}>
              <li>Violate any applicable law or regulation</li>
              <li>Upload malicious content, viruses, or harmful code</li>
              <li>Attempt to gain unauthorized access to other users&apos; data or accounts</li>
              <li>Interfere with or disrupt the Service or its infrastructure</li>
              <li>Scrape, crawl, or use automated means to access the Service</li>
              <li>Impersonate another person or misrepresent your identity</li>
            </ul>
          </section>

          {/* 6. Intellectual Property */}
          <section>
            <h2 className="text-xl md:text-2xl font-bold mb-4">6. Intellectual Property</h2>
            <p className="leading-relaxed" style={{ color: 'var(--color-text-muted)' }}>
              The HealthTrack software is open source and licensed under the{' '}
              <a
                href="https://github.com/tyriekfv/healthtrack/blob/main/LICENSE"
                target="_blank"
                rel="noopener noreferrer"
                className="underline"
                style={{ color: 'var(--color-text-muted)' }}
              >
                MIT License
              </a>
              . The MIT License governs your rights to the software itself, including your rights
              to use, copy, modify, and distribute it. Content you store on an instance of the
              Service remains yours (see Section 8, Data Ownership). Nothing in these Terms limits
              the rights granted to you by the MIT License.
            </p>
          </section>

          {/* 7. Third-Party Integrations */}
          <section>
            <h2 className="text-xl md:text-2xl font-bold mb-4">7. Third-Party Integrations</h2>
            <p className="leading-relaxed mb-3" style={{ color: 'var(--color-text-muted)' }}>
              HealthTrack integrates with third-party services including:
            </p>
            <ul className="list-disc list-inside space-y-2 mb-3" style={{ color: 'var(--color-text-muted)' }}>
              <li>
                <strong>Oura Ring</strong> — for syncing vitals and sleep data with your consent
              </li>
              <li>
                <strong>Google</strong> — for OAuth authentication
              </li>
              <li>
                <strong>Anthropic Claude</strong> — for AI-powered health analysis and lab parsing
              </li>
            </ul>
            <p className="leading-relaxed" style={{ color: 'var(--color-text-muted)' }}>
              These integrations are subject to the respective third parties&apos; terms of service
              and privacy policies. We are not responsible for the availability, accuracy, or
              practices of third-party services.
            </p>
          </section>

          {/* 8. Data Ownership */}
          <section>
            <h2 className="text-xl md:text-2xl font-bold mb-4">8. Data Ownership</h2>
            <p className="leading-relaxed" style={{ color: 'var(--color-text-muted)' }}>
              You own your health data. HealthTrack does not claim ownership of any health
              information you enter into the Service. You may export your data in JSON format at any
              time, and you may delete your data or your entire account whenever you choose. By using
              the Service, you grant us a limited license to process, store, and display your data
              solely for the purpose of providing the Service to you.
            </p>
          </section>

          {/* 9. Limitation of Liability */}
          <section>
            <h2 className="text-xl md:text-2xl font-bold mb-4">9. Limitation of Liability</h2>
            <p className="leading-relaxed" style={{ color: 'var(--color-text-muted)' }}>
              The HealthTrack software is provided free of charge. To the maximum extent permitted
              by law, neither the software authors and contributors nor the operator of any
              self-hosted instance shall be liable for any indirect, incidental, special,
              consequential, or exemplary damages, any loss of data, or any decisions made based on
              information or AI-generated content in the application. This includes, without
              limitation, any damages resulting from reliance on AI-generated health insights, data
              inaccuracies, service interruptions, or unauthorized access to your account. Because
              the software is provided free of charge, total aggregate liability for any claim
              arising from the Service shall not exceed zero dollars ($0).
            </p>
          </section>

          {/* 10. Disclaimer of Warranties */}
          <section>
            <h2 className="text-xl md:text-2xl font-bold mb-4">
              10. Disclaimer of Warranties; Self-Hosted Software
            </h2>
            <p className="leading-relaxed mb-3" style={{ color: 'var(--color-text-muted)' }}>
              HealthTrack is provided on an &quot;as-is&quot; and &quot;as-available&quot; basis
              without warranties of any kind, whether express or implied, including but not limited
              to implied warranties of merchantability, fitness for a particular purpose, and
              non-infringement. We do not warrant that the Service will be uninterrupted,
              error-free, secure, or free of harmful components. We do not warrant the accuracy or
              completeness of any AI-generated content or health insights.
            </p>
            <p className="leading-relaxed" style={{ color: 'var(--color-text-muted)' }}>
              HealthTrack is self-hosted software. Each instance of the Service is operated
              independently by whoever deploys it (&quot;the operator&quot;). The operator — not
              the software authors or contributors — is responsible for the instance&apos;s
              security, availability, backups, lawful operation, and any data stored on it. You use
              any instance at your own risk. The software authors provide the code &quot;as
              is&quot; in accordance with the MIT License.
            </p>
          </section>

          {/* 11. Termination */}
          <section>
            <h2 className="text-xl md:text-2xl font-bold mb-4">11. Termination</h2>
            <p className="leading-relaxed" style={{ color: 'var(--color-text-muted)' }}>
              You may terminate your account at any time by deleting it through the application
              settings. We may suspend or terminate your access to the Service at any time, with or
              without cause, and with or without notice. Upon termination, your right to use the
              Service ceases immediately. We recommend exporting your data before deleting your
              account, as deletion is permanent.
            </p>
          </section>

          {/* 12. Governing Law */}
          <section>
            <h2 className="text-xl md:text-2xl font-bold mb-4">12. Governing Law</h2>
            <p className="leading-relaxed" style={{ color: 'var(--color-text-muted)' }}>
              These Terms shall be governed by and construed in accordance with the laws of the
              United States. Any disputes arising from these Terms or the Service shall be resolved
              through good-faith negotiation. If negotiation fails, disputes shall be submitted to
              binding arbitration in accordance with applicable rules. Because self-hosted
              instances are operated independently, individual operators may be subject to the laws
              of their own jurisdiction; the governing-law and arbitration provisions above apply
              to the software project itself.
            </p>
          </section>

          {/* 13. Changes to Terms */}
          <section>
            <h2 className="text-xl md:text-2xl font-bold mb-4">13. Changes to Terms</h2>
            <p className="leading-relaxed" style={{ color: 'var(--color-text-muted)' }}>
              We reserve the right to modify these Terms at any time. When we do, we will revise the
              &quot;Effective date&quot; at the top of this page. Continued use of the Service after
              changes constitutes acceptance of the updated Terms. We encourage you to review these
              Terms periodically.
            </p>
          </section>

          {/* 14. Contact Information */}
          <section>
            <h2 className="text-xl md:text-2xl font-bold mb-4">14. Contact Information</h2>
            <p className="leading-relaxed" style={{ color: 'var(--color-text-muted)' }}>
              If you have questions about these Terms of Service, please contact your instance
              administrator.
            </p>
          </section>
        </div>
      </main>

      {/* ---------- Footer ---------- */}
      <footer
        className="px-6 py-8 text-center text-sm"
        style={{
          borderTop: '1px solid var(--border-card)',
          color: 'var(--color-text-muted)',
        }}
      >
        <div className="flex flex-col items-center gap-2">
          <div className="flex items-center gap-1">
            <span className="font-bold" style={{ color: 'var(--color-sage)' }}>
              Health
            </span>
            <span className="font-bold" style={{ color: 'var(--color-text-primary)' }}>
              Track
            </span>
          </div>
          <div className="flex items-center gap-4">
            <Link href="/privacy" className="no-underline hover:underline" style={{ color: 'var(--color-text-muted)' }}>
              Privacy Policy
            </Link>
            <Link href="/terms" className="no-underline hover:underline" style={{ color: 'var(--color-text-muted)' }}>
              Terms of Service
            </Link>
          </div>
          <p>&copy; 2026 HealthTrack. All rights reserved.</p>
        </div>
      </footer>
    </div>
  );
}
